Fix bug at end of test code where it tried to free() an uninitialized block

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -13,9 +13,9 @@ jobs:
     strategy:
       matrix:
         sys:
-          - { os: windows-latest, shell: 'msys2 {0}' }
           - { os: ubuntu-latest,  shell: bash  }
           - { os: macos-latest,   shell: bash  }
+          - { os: windows-latest, shell: 'msys2 {0}' }
     defaults:
       run:
         shell: ${{ matrix.sys.shell }}
@@ -31,4 +31,7 @@ jobs:
       - name: make
         run: make clean && make -j
       - name: make check
-        run: make check -j
+        run: |
+          # Test output is too verbose, so only show it if something fails.
+          testout="$(make check -j 2>&1)" &&
+          echo "tests passed" || (echo "$testout"; exit 1)
